### ISSUE TITLE
Error cloning repo

### ISSUE THREAD

**Issue by matthew-unum** [bugsee/flutter-bugsee#4]
I'm trying to include the bugsee dependency in a flutter application but I'm getting a git error.

```
dependencies:
   bugsee:
    git:
      url: git@github.com:bugsee/flutter-bugsee.git
```

```
Git error. Command: `git clone --mirror git@github.com:bugsee/flutter-bugsee.git ~/Development/flutter/.pub-cache/git/cache/flutter-bugsee-dc29691f8b3733b6a71e8f6095488abd97630e7d`
stdout: 
stderr: Cloning into bare repository '~/Development/flutter/.pub-cache/git/cache/flutter-bugsee-dc29691f8b3733b6a71e8f6095488abd97630e7d'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```
